all:
	pdflatex beethoven.tex
	pdflatex beethoven.tex
	pdflatex beethoven.tex
	pdflatex tchaikovsky.tex
	pdflatex tchaikovsky.tex
	pdflatex tchaikovsky.tex
	pdflatex dvorak.tex
	pdflatex dvorak.tex
	pdflatex dvorak.tex
	cp *.pdf /Users/psu/Google/Reader/ARG
