all: scott-main.tex
	pdflatex scott-1979-cmr.tex
	pdflatex scott-1979-pal.tex
	pdflatex scott-1979-ch.tex
	pdflatex scott-1979-pal-eu.tex
	cp scott-1979-pal.pdf /Users/psu/Dropbox/GoodReader/Math\ and\ Physics/Types\,\ etc/
	cp scott-1979-cmr.pdf /Users/psu/Dropbox/GoodReader/Math\ and\ Physics/Types\,\ etc/
	cp scott-1979-ch.pdf /Users/psu/Dropbox/GoodReader/Math\ and\ Physics/Types\,\ etc/
	cp scott-1979-pal-eu.pdf /Users/psu/Dropbox/GoodReader/Math\ and\ Physics/Types\,\ etc/

clean:
	rm -rf *.out *.log *.aux *sync*

.PHONY: clean
