DEST="/Users/psu/Google/Reader/Math and Physics/More Math/Cons \& Logic"

all:
	pdflatex lambek-1984-pal.tex
	pdflatex lambek-1984-pal.tex
	pdflatex lambek-1984-pal.tex
	pdflatex lambek-1984-cmr.tex
	pdflatex lambek-1984-cmr.tex
	pdflatex lambek-1984-cmr.tex
	
	cp lambek-1984-pal.pdf "/Users/psu/Google/Reader/Math and Physics/AAA Inbox/lambek-1984-pal.pdf"
	cp lambek-1984-cmr.pdf "/Users/psu/Google/Reader/Math and Physics/AAA Inbox/lambek-1984-cmr.pdf"

clean:
	rm -rf *.out *.log *.aux *sync*

.PHONY: clean
