#!/bin/sh

# arxsrc - download pdf and source code for arxiv things.
#
# based on the following:
#
# arxpdf - Retrieve arXiv preprints as PDFs
# Copyright (C) 2019 Matthew Kukla <matt.kukla@yandex.ru>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

VERSION=0.1.0
URL=https://arxiv.org/pdf/
PURL=https://arxiv.org/e-print/

usage(){
echo 'Usage: arxpdf [arXiv id]... to download a PDF of [arXiV id]...'
echo '       arxpdf [arXiv id]vn... to download the nth version of [arXiV id]'
echo
echo 'arxpdf accepts both the old arXiv identifier format (subject.SC/YYMMNNN)'
echo 'and the current identifier format (YYMM.number).'
echo
echo 'For more about arXiv identifiers, see arxiv.org/help/arxiv_identifier'
echo
echo 'Options:'
echo '-h, --help        Show this message'
echo '-v, --version           Show version number'
exit
}

# Failure message for corrupt PDF
fail_verify(){
echo "Error downloading arXiv:$1 (file corrupted)"
}

# Failure message for curl 
fail_connect(){
echo "Error: connection to the arXiv failed"
}

# Check that the PDF isn't corrupt and has downloaded in its entirety 
verify(){
    if [ "$(tail -n 1 "$1".pdf )"  != "%%EOF" ]; then
        fail_verify $1
        rm $1.pdf
    fi
}

if [ $# = 0 ]; then
    usage
    exit 0
fi

while [ "$#" -gt 0 ]; do
# Download using current identifier format
    if echo "$1" | grep '^[0-9]\{4\}\.[0-9]\{5\}\(v[0-9]\)\?$' -q ; then
        echo $1
        mkdir ~/arxiv-psu/$1
        cd ~/arxiv-psu/$1
        if ! curl  $URL/$1.pdf -o $1.pdf -s; then
            fail_connect
        else
            verify $1
        fi 
# also grab the e-print source. untar the tarball, or redownload as .tex if the tarball fails.
        if ! curl  $PURL/$1 -o $1.tgz -s; then
            fail_connect
        fi
        tar xfvz $1.tgz
        if [ $? -eq 1 ]; then
            if ! curl  $PURL/$1 -o $1.tex -s; then
                fail_connect
            fi
        fi
        rm $FILE.tgz
        git add .
        git status
        shift

# Download using old identifier format
    elif echo $1 | grep '.\/[0-9]\{7\}\(v[0-9]\)\?$' -q; then
        FILE=$(printf '%s' "$1" | tr '/' '-')
        echo $FILE
        
        mkdir ~/arxiv-psu/$FILE
        cd ~/arxiv-psu/$FILE
        if ! curl $URL/$1.pdf -o $FILE.pdf -s; then
            fail_connect
        else   
            verify $FILE
        fi 
        if ! curl  $PURL/$1 -o $FILE.tgz -s; then
            fail_connect
        fi
        tar xfvz $FILE.tgz
        if [ $? -eq 1 ]; then
            if ! curl  $PURL/$1 -o $FILE.tex -s; then
                fail_connect
            fi
        fi
        rm $FILE.tgz
        git add .
        git status   
        shift

    elif [ $1 = '--help' ] || [ $1 = '-h' ]; then       
        usage
        exit
    
    elif [ $1 = '--version' ] || [ $1 = '-v' ]; then
        echo $VERSION
        exit

    else 
        echo "Unknown option: $1"
        usage
        exit 1
    fi   
done
