#!/bin/sh

cd
base=`basename "$1" .pdf`
echo $base
dir=`dirname "$1"`
echo $dir

m=$2
margin=${m:-30}
echo "Using margin $m"

cp "$1" t.pdf
echo running pdf-crop-margins -u -s $3 -p $margin  t.pdf -o test.pdf

pdf-crop-margins -v -u -s $3 -p $margin  t.pdf -o test.pdf

cp test.pdf "$dir/$base (small).pdf"
