#!/bin/sh

cd
base=`basename "$1" .pdf`
echo $base
dir=`dirname "$1"`
echo $dir

cp "$1" t.pdf
echo pdf-crop-margins --gsFix -u -s $2 -p 40  t.pdf -o test.pdf

pdf-crop-margins --gsFix -v -u -s $2 -p 40  t.pdf -o test.pdf

cp test.pdf "$dir/$base (small).pdf"

open -a "PDF Expert" "$dir/$base (small).pdf"
