#!/bin/sh

cd
base=`basename "$1" .pdf`
echo $base
dir=`dirname "$1"`
echo $dir

cp "$1" t.pdf
echo pdf-crop-margins --gsFix -v -u -s -p 100 -a4 $2 $3 $4 $5  t.pdf -o test.pdf

pdf-crop-margins --gsFix -v -u -s -p 100 -a4 $2 $3 $4 $5  t.pdf -o test.pdf

cp test.pdf "$dir/$base (small).pdf"

open -a "PDF Expert" "$dir/$base (small).pdf"

