#!/bin/sh

cd
base=`basename "$1" .pdf`
echo $base
dir=`dirname "$1"`
echo $dir

pages=$6

echo $pages

if [ ! $pages == "" ]; then
    pages="--pages $pages"
fi

cp "$1" t.pdf
echo pdf-crop-margins -v -u -s -p 100 -a4 $2 $3 $4 $5 $pages  t.pdf -o test.pdf

pdf-crop-margins -v -u -s -p 100 -a4 $2 $3 $4 $5 $pages t.pdf -o test.pdf

cp test.pdf "$dir/$base (small).pdf"

open -a "PDF Expert" "$dir/$base (small).pdf"
