#!/bin/sh

doi2bibcure "$*" | perl -ne 'print unless /month =/;' | perl -pe 'if (/@article/) { s/_//g }'

doi2bibcure "$*" | perl -ne 'print unless /month =/;' | perl -pe 'if (/@article/) { s/_//g }' | pbcopy
