#!/bin/bash

file="$1"
line="$2"

[ "${file:0:1}" == "/" ] || file="${PWD}/${file}"
[ "${line}" == "" ] && line=1

exec osascript << EOF
  set texFile to POSIX file "${file}"
  tell application "TeXShop"
    activate
    open texFile
    tell front document
      refreshtext
      goto line ${line}
    end tell
  end tell
EOF
