all: lambek-1980-ccc-pal-eu.tex lambek-main.tex
	pdflatex lambek-1980-ccc-pal-eu.tex
	pdflatex lambek-1980-ccc-pal-eu.tex
	pdflatex lambek-1980-ccc-pal-eu.tex


clean:
	rm -rf *.out *.log *.aux *sync*

.PHONY: clean
