all:
	pdflatex lambek-1980-pal.tex
	pdflatex lambek-1980-pal.tex
	pdflatex lambek-1980-pal.tex
	pdflatex lambek-1980-cmr.tex
	pdflatex lambek-1980-cmr.tex
	pdflatex lambek-1980-cmr.tex
	lualatex lambek-1980-ch.tex
	lualatex lambek-1980-ch.tex
	lualatex lambek-1980-ch.tex
	pdflatex lambek-1980-lucida.tex
	pdflatex lambek-1980-lucida.tex
	pdflatex lambek-1980-lucida.tex
	cp lambek-1980-pal.pdf "/Users/psu/Library/CloudStorage/Dropbox/GoodReader/Math and Physics/More Math/Cons & Logic/Lambek - From λ-Calculus to Cartesian Closed Categories (1980,pal).pdf"
	cp lambek-1980-cmr.pdf "/Users/psu/Library/CloudStorage/Dropbox/GoodReader/Math and Physics/More Math/Cons & Logic/Lambek - From λ-Calculus to Cartesian Closed Categories (1980,cmr).pdf"
	cp lambek-1980-ch.pdf "/Users/psu/Library/CloudStorage/Dropbox/GoodReader/Math and Physics/More Math/Cons & Logic/Lambek - From λ-Calculus to Cartesian Closed Categories (1980,ch).pdf"
	cp lambek-1980-lucida.pdf "/Users/psu/Library/CloudStorage/Dropbox/GoodReader/Math and Physics/More Math/Cons & Logic/Lambek - From λ-Calculus to Cartesian Closed Categories (1980,luc).pdf"

clean:
	rm -rf *.out *.log *.aux *sync*

.PHONY: clean
