all:
	pdflatex lambek-1980-pal.tex
	pdflatex lambek-1980-pal.tex
	pdflatex lambek-1980-pal.tex
	pdflatex lambek-1980-cmr.tex
	pdflatex lambek-1980-cmr.tex
	pdflatex lambek-1980-cmr.tex
	pdflatex lambek-1980-ch.tex
	pdflatex lambek-1980-ch.tex
	pdflatex lambek-1980-ch.tex
	pdflatex lambek-1980-lucida.tex
	pdflatex lambek-1980-lucida.tex
	pdflatex lambek-1980-lucida.tex

clean:
	rm -rf *.out *.log *.aux *sync*

.PHONY: clean
