all: 
	pdflatex yoneda-speedrun.tex
	pdflatex yoneda-speedrun.tex
	pdflatex yoneda-speedrun.tex

	pdflatex yoneda-speedrun-pal.tex
	pdflatex yoneda-speedrun-pal.tex
	pdflatex yoneda-speedrun-pal.tex


	pdflatex yoneda-speedrun-lucida.tex
	pdflatex yoneda-speedrun-lucida.tex
	pdflatex yoneda-speedrun-lucida.tex

	cp yoneda-speedrun.pdf "/Users/psu/Dropbox/GoodReader/Math and Physics/More Math/Cats/yoneda-speedrun.pdf"
	
	cp yoneda-speedrun-pal.pdf "/Users/psu/Dropbox/GoodReader/Math and Physics/More Math/Cats/yoneda-speedrun-pal.pdf"
	
	cp yoneda-speedrun-lucida.pdf "/Users/psu/Dropbox/GoodReader/Math and Physics/More Math/Cats/yoneda-speedrun-lucida.pdf"
	
clean:
	rm -rf *.out *.log *.aux *sync*

.PHONY: clean
