all: 
	pdflatex --synctex=1 yoneda-speedrun.tex
	pdflatex --synctex=1 yoneda-speedrun.tex
	pdflatex --synctex=1 yoneda-speedrun.tex

	pdflatex --synctex=1 yoneda-speedrun-pal.tex
	pdflatex --synctex=1 yoneda-speedrun-pal.tex
	pdflatex --synctex=1 yoneda-speedrun-pal.tex


	pdflatex --synctex=1 yoneda-speedrun-pal-eu.tex
	pdflatex --synctex=1 yoneda-speedrun-pal-eu.tex
	pdflatex --synctex=1 yoneda-speedrun-pal-eu.tex

	pdflatex --synctex=1 yoneda-speedrun-lucida.tex
	pdflatex --synctex=1 yoneda-speedrun-lucida.tex
	pdflatex --synctex=1 yoneda-speedrun-lucida.tex

	cp yoneda-speedrun.pdf "/Users/psu/Desktop/Google/Reader/Math and Physics/More Math/Cats/yoneda-speedrun.pdf"
	
	cp yoneda-speedrun-pal.pdf "/Users/psu/Desktop/Google/Reader/Math and Physics/More Math/Cats/yoneda-speedrun-pal.pdf"
	
	cp yoneda-speedrun-pal-eu.pdf "/Users/psu/Desktop/Google/Reader/Math and Physics/More Math/Cats/yoneda-speedrun-pal-eu.pdf"
	
	cp yoneda-speedrun-lucida.pdf "/Users/psu/Desktop/Google/Reader/Math and Physics/More Math/Cats/yoneda-speedrun-lucida.pdf"
	
clean:
	rm -rf *.out *.log *.aux *sync*

.PHONY: clean
