#! /bin/bash
# You need to change the runhugs path
echo "Generating html for tutorial in ./html"
echo "Run this twice to get references right"
echo "Report must be in ../report for hyperlinks to work"
rm -fr html
mkdir html
cp *.gif html
cp *.html html
cp -r code html
runhugs tex.hs
